### ISSUE TITLE
security vulnerabilities in dependent packages, and ugly Warnings/Messages

### ISSUE THREAD

**Issue by DickBaker** [GemBox-d-o-o/GemBox.Pdf.Examples#3]
VS2022 (mine=v17.12.0 prev 2.1) and NuGet report **security issues** (affects net48 and net8.0)
Package   'System.Private.Uri' 4.3.0 has a known high severity vulnerability,   https://github.com/advisories/GHSA-5f2m-466j-3848
Package 'System.Private.Uri' 4.3.0 has a   known high severity vulnerability,   https://github.com/advisories/GHSA-xhfc-gr8f-ffwc
Package 'System.Private.Uri' 4.3.0 has a   known moderate severity vulnerability,   https://github.com/advisories/GHSA-x5qj-9vmx-7g6g
Package 'System.Text.Json' 8.0.0 has a   known high severity vulnerability,   https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

and there are 2 compilation **ERRORs** on the PdfMaui project
33.0 is not a valid TargetPlatformVersion for Android. Valid versions include: 34.0
15.4 is not a valid TargetPlatformVersion for iOS. Valid versions include: 17.0 17.5

and there are 9 outdated packages

| package | as-is ver | to-be ver |
| - | - | - |
| HarfBuzzSharp.NativeAssets.WebAssembly | 7.3.0.1 | 7.3.0.2 |
|Microsoft.AspNetCore.Components.WebAss|8.0.1|8.0.8|
|Microsoft.AspNetCore.Components.WebAssembly.De|8.0.1|8.0.8|
|Microsoft.Azure.Functions.Worker|1.20.1|1.23.0|
|Microsoft.Azure.Functions.Worker.Extensions.Http|3.1.0|3.2.0|
|Microsoft.Azure.Functions.Worker.Sdk|1.16.4|1.18.0|
|Microsoft.Maui.Controls|8.0.82|8.0.91|
|Microsoft.Maui.Controls.Compatibility|8.0.82|8.0.91|
|SkiaSharp.NativeAssets.WebAssembly|2.88.7|2.88.8|

an Update to the non-MAUI MS packages works, but attempting either MAUI package update reverts the other
and hand-editing the PdfMaui.csproj to "8.0.91" also reverts both to "8.0.82", but this is probably due to those earlier Errors about platform-specific target versions so I have chosen to simply ignore that MAUI project (I am a MAUI movice).

There are also a slew of **Warning/Messages** that are ugly/scary and IMHO I suggest these should be improved

|count|Severity|Code|Description (abbrev)|
|-|-|-|-|
|2|Message|CA1050|Declare types in namespaces|
|1|Message|CA1822|Members that do not access instance data or call i|
|1|Message|CA1835|'Stream' has a 'ReadAsync' overload that takes a '|
|1|Message|CA1859|Using concrete types avoids virtual or interface c|
|20|Message|IDE0017|Object initialization can be simplified|
|4|Message|IDE0031|Null check can be simplified|
|1|Message|IDE0042|Variable declaration can be deconstructed|
|2|Message|IDE0045|'if' statement can be simplified|
|2|Message|IDE0052|Private member 'ErrorModel._logger' can be removed|
|4|Message|IDE0053|Use expression body for lambda expression|
|2|Message|IDE0057|Substring can be simplified|
|114|Message|IDE0063|'using' statement can be simplified|
|1|Message|IDE0074|Use compound assignment|
|12|Message|IDE0090|'new' expression can be simplified|
|4|Message|IDE0290|Use primary constructor|
|15|Message|IDE0300|Collection initialization can be simplified|
|1|Warning|MA002|Starting with .NET 8, setting  <UseMaui>true</UseM|
|6|Warning|NU1902|Package 'System.Private.Uri' 4.3.0 has a known mod|
|13|Warning|NU1903|Package 'System.Private.Uri' 4.3.0 has a known hig|
|15|Message|RCS1001|Add braces to for/foreach/using statement (when ex|
|3|Message|RCS1003|Add braces to if-else (when expression spans over |
|3|Message|RCS1021|Use expression-bodied lambda|
|14|Message|RCS1037|Remove trailing white-space|
|52|Warning|RCS1102|Make class static|
|51|Message|RCS1110|Declare '...' inside namespace|
|17|Message|RCS1118|Mark local variable as const|
|35|Message|RCS1123|Add parentheses when necessary|
|1|Message|RCS1128|Use coalesce expression|
|6|Message|RCS1146|Use conditional access|
|1|Message|RCS1163|Unused parameter 'sp'|
|3|Message|RCS1251|Remove unnecessary braces|
|1|Message|RCS1261|Resource can be disposed asynchronously|
|2|Message|SYSLIB1045|Use 'GeneratedRegexAttribute' to generate the regu|

Anyway, many thanks for this very useful **GH** resource and for offering the Free licensing option.
I hope that this Issue will further enhance the repo

regards,
Dick

**Comment by mario-gembox** [comment]
Hi @DickBaker 

We have fixed the issue with the MAUI project and updated the outdated packages.
We'll commit these changes and some additional example updates together with the next public release of GemBox.Pdf (sometime at the beginning of next week).

Regarding the rest, other updates won't be done at the moment.

Regards,
Mario

**Comment by mario-gembox** [comment]
Hi @DickBaker

The packages have been updated.

Regards,
Mario
